### ISSUE TITLE
Ingestion of csv files in datahub

### ISSUE THREAD

**Issue by PriyaShaji** [linkedin/datahub#1552]
Is there an option to upload csv files as datasets into the datahub?

**Comment by ben5448** [comment]
Someone can write an import utility to pull in CSV, but I don't know a standard way to represent all the arrays and data structures in a flat file. Using JSON provides more structure to the data.

**Comment by PriyaShaji** [comment]
Thank you @ben5448 , so that means in order to import/add dataset we can do it via `mce_cli.py` by passing the respective `dat` file to it.

**Comment by ben5448** [comment]
You can do that. If you look at what mce_cli.py is doing, it is taking JSON data that is written 1 line/record and sending that to kafka. There is not much more going on. That means if you export your data into the correct JSON structure with a single line per record, mce_cli.py can transmit it to datahub.

The other utilities under metadata-ingestion extract information from a data source like LDAP, kafka, or a database to create the data structure. Those utilities send data directly to the kafka component of datahub without writing to a file.

To deal with security contraints, I modified one of those utilities to pull the information I needed and write it to a file instead of sending to kafka. Then I used mce_cli.py to send that data to datahub.

The ingestion scripts should be your starting point to pull information into datahub. They will likely need to be modified to fit your requirements. For example my LDAP config was somewhat different from what the ldap-etl script expected.

**Comment by keremsahin1** [comment]
Hi @PriyaShaji 

`mce_cli` is a simple script which reads from a file line by line and sends those messaged to Kafka, MetadataChangeEvent topic to be specific. It doesn't do any transformation and it doesn't contain any logic.

That being said, any line in your input file should conform to the schema of the Kafka topic. The schema for this topic is automatically generated from https://github.com/linkedin/datahub/blob/master/metadata-models/src/main/pegasus/com/linkedin/mxe/MetadataChangeEvent.pdsc. This is the Pegasus schema. By using a plugin, it's converted to Avro and it's being used as the schema on the Kafka topic. You can also check the schema on the `schema-registry-ui` by connecting http://localhost:8000.  It's another application just for debugging purposes and should be already up if you are using quickstart script.

Hope that's clear for you,
Kerem

**Comment by mars-lan** [comment]
@keremsahin1 & @ben5448  I'm not sure if that's what @PriyaShaji is actually asking. I think what she was asking is that if we can represent a CSV file as a dataset in DataHub. For that, you'll just need to emit a MCE that contains the https://github.com/linkedin/datahub/blob/master/metadata-models/src/main/pegasus/com/linkedin/schema/SchemaMetadata.pdsc info for the CSV file

**Comment by PriyaShaji** [comment]
Thankyou @mars-lan . Is there an example for this on how to emit the MCE which contains the info[SchemaMetadata](https://github.com/linkedin/datahub/blob/master/metadata-models/src/main/pegasus/com/linkedin/schema/SchemaMetadata.pdsc) for csv file?

**Comment by PriyaShaji** [comment]
Hi @keremsahin1 @ben5448 , Yes the execution process of how the data is bootstrapped into datahub is clear to me now:), The ingestion scripts in metadata-ingestion is platform specific and depends on the developer on how to extend it as per their ETL use case.

**Comment by mars-lan** [comment]
@PriyaShaji  here's an example. It's for Kafka but it's essentially the same: https://github.com/linkedin/datahub/blob/master/metadata-ingestion/kafka-etl/kafka_etl.py#L19
