### ISSUE TITLE
decouple gms and metadata-jobs

### ISSUE THREAD

**Issue by clojurians-org** [linkedin/datahub#1598]
currently mce job send data to gms api, and gms send data to mae topic.

we can doucple gms and metadata-jobs 

mce job: [mce topic] -> [gms request topic], 
mae job: [mae topic] -> ([es, neo4j]/gms request topic)

gms: offer wrapper api to write to gms request topic
so that 
1. multiple gms instance(just like kafka-streams compute engine rebalance mechanism) or 
2. gms offline for some period, or 
3. multiple gms version coexist for upgrade(add version field for topic message). 
4. etl-jobs don't care about store-dao, only topic matter for decoupling different store backend.

**Comment by clojurians-org** [comment]
event we can build two topic only.
pipeline channel(mce, mae) <-> gms channel

then in datahub-pipeline, we branch to mce, mae event processing, and write back to gms channel.

we can add more event to datahub-pipeline channel also for general event processing mechanism

**Comment by mars-lan** [comment]
This is an interesting ask and may have fundamental implication to the architecture. To help us understand better, are you suggesting something like this

```
Metadata provider --> MCE topic --> MCE job -+-> MAE topic --> MAE job
                                             |
                                             +-> new GMS topic --> GMS
```

**Comment by clojurians-org** [comment]
yeah, that's my thought.
so  we can future split mae evevent to mae search event and mae graph event or more..
and push down the job-dao operation to gms so that we can use professional kafka streams computing framework without  outside world careless.
the deploy is more easily if we add more event later as we have one unified event framework.

**Comment by clojurians-org** [comment]
kafka stream have branch function, and support subscribe by mutiple or glob topic.
we only need one gms  job only, then branch to other processing logic.in this way.
in this way, we don't split job by function rather than split job to gms internal  job and and (external hook job in future)


https://kafka.apache.org/20/javadoc/org/apache/kafka/streams/kstream/KStream.html#branch-org.apache.kafka.streams.kstream.Predicate...-

**Comment by mars-lan** [comment]
Thanks for the suggestion. The problem with Kafka streams state store is that it's not a persistent storage and is not queriable outside of Kafka. The main difference between MCE & MAE is that the latter signals that the metadata has been committed to a persistent storage that can then be subsequently queried via GMS. You can also think of it as a standardized CDC stream.

**Comment by clojurians-org** [comment]
the gms can receive the kafka stream (graph, search) event, and persist  to storage.
so that gms only care about the store, job only care about the streaming.

if we switch neo4j to janusgraph, i need to rebuild the job and gms.
if we decouple the store to gms, we don't need to care about job. it's the standard event message format. the gms care about the store dao mapping only.

**Comment by mars-lan** [comment]
I see where you're coming from. However, MAE is such an important message conveying the fact that the metadata has been committed to the storage and thus can be immediately fetched via GMS. Not upholding that contract will fundamentally alter the architecture and lead to potential race conditions (e.g. when an aspect is updated both via MCE and via GMS API call).

That said, your suggestion on decoupling graph builder logic from actual graph update is spot on. Internally we're trying to add an extra job that consumes MAE, runs the graph builder logic, and emits MGE (MetadataGraphEvent, consists of just node & edge updates). After that, one just need to focus on an implementation-specific MGE job (e.g. neo4j MGE job vs JanuasGraph MGE job), without worrying about the graph builder logics. In fact, you can even configure your stream processor so that it updates neo4j & JanuasGraph simultaneously.

Here's a summary of what it'll looks like

```
MCE --> MCE job ---> GMS --> MAE --> MAE graph job --> MGE -+-> MGE neo4j job --> neo4j
                                                            |
                                                            +-> MGE JanuasGraph job --> JanuasGraph
```

**Comment by clojurians-org** [comment]
the whole architecture can be thought to  contains three part:
  computing, store, view.
currently, 
  mce = computing
  gms = store(api) + view
  mae = computing + store

the job can contains the computing-job + store-job, and gms do view only.
the store job can be implemented by store plugin(neo4j, JanuasGraph)'

or job can do computing only, and gms do store + view.

**Comment by mars-lan** [comment]
That's a good way to think of the architecture. However, I'd like to break "compute" into various kind of "business logic". In that case, the current architecture is

MCE job = ingest business logic (simple passthrough from MCE to GMS api calls)
GMS = create/update business logic, store (to DB), view
MAE job = index business logic, store (to search & graph)

As suggested, one option is to move the create/update business logic from GMS to MCE/MAE job, and possibly even have the job directly stores the result into DB. However, if we ever need to support API-based synchronous update (for read-after-write consistency), we'll need to move/duplicate the business logic to/in GMS.

While it seems like metadata is ingested exclusively via MCE in OSS, inside of LinkedIn, there is actually a large portion of metadata that is only updated via GMS APIs. As a result, we chose the current architecture so that we can concentrate the create/update business logic in GMS.

Hope this helps.

**Comment by mars-lan** [comment]
Closing this as we don't intent to fundamentally change the architecture in the short term. Will reopen in the future if the discussion becomes relevant again.
