### ISSUE TITLE
The best way to ingest dataset to datahub

### ISSUE THREAD

**Issue by liangjun-jiang** [linkedin/datahub#1717]
This is a really general question: what's the best way to ingest dataset to datahub.

 I understand there is a `metadata-ingestion` module which highlights some common data source that we can ingest dataset entity into datahub via Kafka.

In an enterprise environment, there are many data resources, I make up a way that that we can set up Airflow job to periodically scan my Hive metadata table, and ingest table schema as dataset. Hopefully, each table comes with a dataset owner info so I can fill in all dataset aspects. 

In this approach, the developers of datahub also plays roles of an ETL engineer to proactively ingesting data to datahub. 

Do we have the other way that the data table / database owners can send data to datahub without too much work on their sides. No one wants to manually generate Kafka message, or modify a metadata to include some information such as dataset owner's LDAP account. 

I guess, in reality, it would be the combination of those approaches. 

I want to hear what you guys say, and what's the best way or proposed way or suggestion to enable Datahub to max its capacity. 

It will be great that in the next townhall meeting, someone could give some demo how his organization does to bring metadata into datahub.

**Comment by liangjun-jiang** [comment]
for example, I found this article is useful: https://medium.com/albert-franzi/data-catalogue-knowing-your-data-15f7d0724900 
Curious whether there is more written documentation.

**Comment by keremsahin1** [comment]
Thanks for this question @liangjun-jiang . This is definitely an important discussion. 

First of all, there is no right or wrong or best way of doing things. You can ingest or bring in metadata to DataHub in two ways: through GMS Rest APIs (sync) or through Kafka messages (async). DataHub is able to ingest metadata through Kafka events because we have consumer jobs listening on those topics and ingests metadata present in those messaged through GMS Rest APIs again.

> In this approach, the developers of datahub also plays roles of an ETL engineer to proactively ingesting data to datahub.

Yes, that's correct. For the data platforms you want to support within DataHub, you need to implement crawler mechanisms as well. The better way is to instrument data platform itself (if it allows for it) to emit metadata change events by itself when there is a change. There is a small discussion about that in Mars's blog post:

> Push is better than pull: While pulling metadata directly from the source seems like the most straightforward way to gather metadata, developing and maintaining a centralized fleet of domain-specific crawlers quickly becomes a nightmare. It is more scalable to have individual metadata providers push the information to the central repository via APIs or messages. This push-based approach also ensures a more timely reflection of new and updated metadata.

Source: https://engineering.linkedin.com/blog/2019/data-hub

Hope this answers your question.

**Comment by liangjun-jiang** [comment]
Thanks. @keremsahin1 . It helped me answer part of my questions. Especially, the push vs. pull approach. As a tool provider, I definitely want other parties to conform the data contract I defined, and provided the data with all information(ownership, upstream and downstream lineage, schema, etc if use `dataset` entity as an example) to me.

My question is that how other parties (the data source owners) could provide the dataset with complete aspects to me?  Let's use `mysql-etl` python script as an example
```
owner = {"owners":[{"owner":actor,"type":"DATAOWNER"}],"lastModified":{"time":0,"actor":actor}}

    for columnIdx in range(len(schema)):
        fields.append({"fieldPath":str(schema[columnIdx][0]),"nativeDataType":str(schema[columnIdx][1]),"type":{"type":{"com.linkedin.pegasus2avro.schema.StringType":{}}}})

    schema_name = {"schemaName":dataset_name,"platform":"urn:li:dataPlatform:mysql","version":schema_version,"created":{"time":sys_time,"actor":actor},
               "lastModified":{"time":sys_time,"actor":actor},"hash":"","platformSchema":{"tableSchema":str(schema)},
               "fields":fields}

    mce = {"auditHeader": None,
           "proposedSnapshot":("com.linkedin.pegasus2avro.metadata.snapshot.DatasetSnapshot",
                               {"urn": "urn:li:dataset:(urn:li:dataPlatform:mysql,"+ dataset_name +",PROD)","aspects": [owner, schema_name]}),
           "proposedDelta": None}
```
In this MCE, we know `platform` is `msyql`; We are able to find `schema` information; We don't really know who is `data owner`;  we definitely won't be able to find `lineage` information. 
I understand that it should be the responsibility of data owner to provide those information. If the data sources of an organization couldn't provide all information that `dataset` entity is needed, it makes the `datahub` less useful even though datahub does provide many useful features.   

I guess my real question is, internally how do your metadata providers assemble information needed for a dataset? 
Do they also just put `datahub` as data owner? or they have a field in the table schema so they put the LDAP username as data owner in MySQL ? how do they gather `upstream lineage` or `downstream lineage` information? 

Once again, I know this is not datahub's scope of work. I think a general guidance would be very helpful. The guidance should highlights a few things: 
1. insert data owner in the schema or somewhere for the database
2. if it's data lake such as Hive,  keep the information how a hive table is created and ingested (by a ETL script or what?)

Hope this would clarify my question better.

**Comment by keremsahin1** [comment]
Thanks for detailed explanation with examples @liangjun-jiang .

> My question is that how other parties (the data source owners) could provide the dataset with complete aspects to me?

Short answer to your question: they don't have the provide complete aspects. Data platform itself doesn't have to be the SOT for all the metadata types. Ownership metadata for datasets is a good example. You generally can't extract the ownership info from the data platform. For the metadata you can't extract from the SOT, our general approach is to get it from the users manually. That's the reason DataHub provides you an interface to update ownership metadata. And, DataHub itself becomes the SOT for ownership metadata. You don't need to store this metadata in the data platform itself (although you can if you want to).

And yes, collecting this metadata is painful because it's up-to the owners to go ahead and claim the ownership. Although, it's not OS, LinkedIn production DataHub has this feature called "Suggested Owners". We have flows/crawlers which process different sources/logs where we can find the potential owners and surface this information on the ownership tab. Also, there are some other flows which monitor for these missing metadata (ownership in this case) and send notifications/reminders to help collecting this metadata.

> how do they gather upstream lineage or downstream lineage information?

Lineage is a different beast. But the approach we take here is similar to what I've described earlier. This is highly platform specific. Depending on the platform type, you can crawl this metadata from the data source itself (logs of ETL jobs, workflow managers like [Azkaban](https://azkaban.github.io/) etc.) or instrument the job/process which moves the data around (like [Gobblin](https://gobblin.apache.org/)) to send this metadata to DataHub.

**Comment by liangjun-jiang** [comment]
Thanks again. By the time I works for Alibaba Group, we have an internal tool. Every application database related changes, we need to go through that took to make a change request. The request have to contain information. The database/table owner will review the request,  either approve or decline. 
The minimum requirement of this request needs to have
1. SQL scripts (create, insert, update,  or delete, etc)

In this centralized approach, Alibaba's data warehouse is able to capture every information needed 
1. database/table has already had owner assigned.
2. since each SQL statement will be executed in this centralized tool, it will be much easier to parse lineage information based on the SQL. 

Of course, this is not only a problem of available tool, but also how a rule needs to be setup and  enforced for developers.
