### ISSUE TITLE
elasticsearch-setup operation is not compatible with es 6.x or 7.x version

### ISSUE THREAD

**Issue by cobolbaby** [linkedin/datahub#1722]
**Describe the bug**

When I start the elasticsearch-setup container, Something is wrong with ES v7.7.1:

```
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
```

When I add the `Content-Type` header, The following exception is reported:

```
dev@docker-build-1:/opt/datahub/docker/elasticsearch$ curl -sS -XPUT 10.191.7.1:9200/corpuserinfodocument -H 'Content-Type: Application/JSON' --data @corpuser-index-config.json | jq .
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "Root mapping definition has unsupported parameters:  [doc : {properties={skills={type=text}, urn={normalizer=custom_normalizer, type=keyword}, teams={type=text}, ldap={analyzer=lowercase_keyword, type=text, fields={ngram={analyzer=delimit_edgengram, type=text}}}, managerLdap={analyzer=lowercase_keyword, type=text, fields={ngram={analyzer=delimit_edgengram, type=text}}}, active={type=boolean}, fullName={type=text, fields={ngram={analyzer=delimit_edgengram, type=text}}}, title={normalizer=custom_normalizer, type=keyword}, aboutMe={type=text}}}]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [doc : {properties={skills={type=text}, urn={normalizer=custom_normalizer, type=keyword}, teams={type=text}, ldap={analyzer=lowercase_keyword, type=text, fields={ngram={analyzer=delimit_edgengram, type=text}}}, managerLdap={analyzer=lowercase_keyword, type=text, fields={ngram={analyzer=delimit_edgengram, type=text}}}, active={type=boolean}, fullName={type=text, fields={ngram={analyzer=delimit_edgengram, type=text}}}, title={normalizer=custom_normalizer, type=keyword}, aboutMe={type=text}}}]",
    "caused_by": {
      "type": "mapper_parsing_exception",
      "reason": "Root mapping definition has unsupported parameters:  [doc : {properties={skills={type=text}, urn={normalizer=custom_normalizer, type=keyword}, teams={type=text}, ldap={analyzer=lowercase_keyword, type=text, fields={ngram={analyzer=delimit_edgengram, type=text}}}, managerLdap={analyzer=lowercase_keyword, type=text, fields={ngram={analyzer=delimit_edgengram, type=text}}}, active={type=boolean}, fullName={type=text, fields={ngram={analyzer=delimit_edgengram, type=text}}}, title={normalizer=custom_normalizer, type=keyword}, aboutMe={type=text}}}]"
    }
  },
  "status": 400
}
```

**Comment by cobolbaby** [comment]
Ref: #1737

**Comment by camelliazhang2018** [comment]
@cobolbaby The error is caused by the breaking change in ES 7.x with the removal of mapping types: 
https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html

**Comment by camelliazhang2018** [comment]
@cobolbaby It is caused by the breaking change in ES 7.x with the removal of mapping types: 
https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html

Have you tried ES 6.x? Our current index mapping put “doc” as type for all indices, and it should be compatible with ES 6.X. 

We will experiment to see if it is possible to create an index mapping that works for all three ES versions. Or, we can create a different version of index mapping for ES 7.x. However, to fully support ES 7.x,  we will need to pay effort on testing  & constructing new queries if necessary.

**Comment by cobolbaby** [comment]
Yes, I have tried ES 6.7.0. It does not support.

**Comment by cobolbaby** [comment]
@camelliazhang2018, In addition I have a question about the fields in the doc. If the current model definition already contains the information I need, do I only need to modify the content defined in index.json .

**Comment by fabiofilz** [comment]
I would like to input some extra information about using the AWS ElasticSearch.

1 - I created a AWS VPC ElasticSearch version 5.6. The next version available is 6.0.
1.1 - I found this link explaining how to access the VPC ElasticSearch https://www.jeremydaly.com/access-aws-vpc-based-elasticsearch-cluster-locally.
1.2 - I am not sure if it will be necessary to amend  the application to use the AWS credentials/profile file in cause it is necessary to authenticate with ElasticSearch using access policy. I switched it off completely in order to be able to test the connectivity between the POD and ElasticSearch.

2 - Creating the index as per Dockerfile (commands below):

curl -XPUT https://vpc-datahub-es-pt-XXXXXXXXXXXXXXX.eu-central-1.es.amazonaws.com:443/corpuserinfodocument --data @corpuser-index-config.json

=> {"acknowledged":true,"shards_acknowledged":true,"index":"corpuserinfodocument"}% 

curl -XPUT https://vpc-datahub-es-pt-XXXXXXXXXXXXXXX.eu-central-1.es.amazonaws.com:443/dataprocessdocument --data @dataprocess-index-config.json

==> {"acknowledged":true,"shards_acknowledged":true,"index":"dataprocessdocument"}

curl -XPUT https://vpc-datahub-es-pt-XXXXXXXXXXXXXXX.eu-central-1.es.amazonaws.com:443/datasetdocument --data @dataset-index-config.json

==> {"acknowledged":true,"shards_acknowledged":true,"index":"datasetdocument"}

3 - Updated the value.yaml
global:
  elasticsearch:
    host: "vpc-datahub-es-pt-XXXXXXXXXXXXXXX.eu-central-1.es.amazonaws.com"
    port: "443"

4 - Deployed the helm charts using the command: helm3 install --namespace datahub datahub datahub/

When I check the logs of the POD I can see the error: **2020/07/24 13:33:13 Received 400 from http://vpc-datahub-es-pt-XXXXXXXXXXXXXXX.eu-central-1.es.amazonaws.com:443. Sleeping 1s**

So I accessed the POD and execute the commands below:

curl https://vpc-datahub-es-pt-XXXXXXXXXXXXXXX.eu-central-1.es.amazonaws.com:443/_cat/indices
yellow open .kibana              YVSOjZ64QoK3PeTF7kX_Lg 1 1 1 0 3.2kb 3.2kb
yellow open corpuserinfodocument x0jqAtFMQcODYrUCC9PzQA 5 1 0 0  810b  810b
yellow open datasetdocument      bosiOF5YRC-X1NzgzYF1YA 5 1 0 0  810b  810b
yellow open dataprocessdocument  LgyAuMFlQYmQjEjftUSjNQ 5 1 0 0  810b  810b

curl https://vpc-datahub-es-pt-XXXXXXXXXXXXXXX.eu-central-1.es.amazonaws.com:443
{
  "name" : "G8HxGZg",
  "cluster_name" : "xxxxxxxxxxx:datahub-es-pt1",
  "cluster_uuid" : "e7FpGywPRDWsxNshu9xKYg",
  "version" : {
    "number" : "5.6.17",
    "build_hash" : "59bb0dx",
    "build_date" : "2020-01-03T11:28:23.851Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
  "tagline" : "You Know, for Search"
}

I changed the logs level to DEBUG, but there is no other details that could help to understand the reason for code 400.

Any idea?

Thank you.
Fabio

**Comment by camelliazhang2018** [comment]
@fabiofilz Hi Fabio, thanks for the sharing the steps in details. Not sure if you need to restart or anything else for log level to take effect. Without that, it is hard to guess what's wrong. For example, you can see a real error message for 400 such as one listed [here](https://github.com/uken/fluent-plugin-elasticsearch/issues/467) .  A few things you may also want to try: 1. Check  the docker size and make sure to allocate at least 8GB of RAM + 2GB swap space. 2. Try a curl call to issue a [match all query ](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-all-query.html)and see what returns?

**Comment by camelliazhang2018** [comment]
@cobolbaby  I am a bit surprised that 6.x does not work, what is the error message for 6.7.0? Per ES documentation:
"Indices created in Elasticsearch 6.0.0 or later may only contain a single mapping type. **Indices created in 5.x with multiple mapping types will continue to function as before in Elasticsearch 6.x.** Types will be deprecated in APIs in Elasticsearch 7.0.0, and completely removed in 8.0.0.." I will try ES 6.x & 7.x and see how we can support. Will keep you posted.

**Comment by camelliazhang2018** [comment]
> @camelliazhang2018, In addition I have a question about the fields in the `doc`. If the current model definition already contains the information I need, do I only need to modify the map relationship in index.json . Ref: #1736
> 
> When improving the index configuration of different versions, can you make up the index.json, such as a table comment information?

I made the comment in that thread. Thanks.

**Comment by cobolbaby** [comment]
@camelliazhang2018 Thx.

**Comment by cobolbaby** [comment]
@camelliazhang2018, When I upgrade the ES version from 5.6.16 to 6.8.11, the ES console will show some prompts:

```
# ES console prompts when the service starts
[2020-07-28T09:41:29,044][WARN ][o.e.d.a.c.NGramTokenizerFactory] [b0pdh5T] Deprecated big difference between max_gram and min_gram in NGram Tokenizer,expected difference must be less than or equal to: [1]
[2020-07-28T09:41:33,565][WARN ][o.e.d.r.a.a.i.RestGetMappingAction] [b0pdh5T] [types removal] The parameter include_type_name should be explicitly specified in get mapping requests to prepare for 7.0. In 7.0 include_type_name will default to 'false', which means responses will omit the type name in mapping definitions.

[2020-07-28T09:41:31,885][WARN ][o.e.c.m.MetaDataMappingService] [b0pdh5T] [datasetdocument] re-syncing mappings with cluster state because of types [[doc]]
[2020-07-28T09:41:33,899][WARN ][o.e.c.m.MetaDataMappingService] [b0pdh5T] [dataprocessdocument] re-syncing mappings with cluster state because of types [[doc]]
[2020-07-28T09:41:36,965][WARN ][o.e.c.m.MetaDataMappingService] [b0pdh5T] [corpuserinfodocument] re-syncing mappings with cluster state because of types [[doc]]

# When searching for keywords
[2020-07-28T09:50:34,656][WARN ][o.e.d.c.ParseField       ] [b0pdh5T] Deprecated field [disable_coord] used, replaced by [disable_coord has been removed]
[2020-07-28T09:50:34,656][WARN ][o.e.d.s.a.I.Parser       ] [b0pdh5T] Deprecated aggregation order key [_term] used, replaced by [_key]
[2020-07-28T09:50:34,657][WARN ][o.e.d.s.a.I.Parser       ] [b0pdh5T] Deprecated aggregation order key [_term] used, replaced by [_key]
```

Although it does not seem to affect the work at present, it is best to adjust the index configuration to ensure that there will be no problems.

**Comment by fabiofilz** [comment]
@camelliazhang2018 Would you mind to confirm how I should increase the log level?
I am using the helm charts to deploy datahub into k8s.

I executed the 
curl https://vpc-datahub-es-pt-XXXXXXXXXXXXxx.eu-central-1.es.amazonaws.com/_search

{"took":17,"timed_out":false,"_shards":{"total":16,"successful":16,"skipped":0,"failed":0},"hits":{"total":1,"max_score":1.0,"hits":[{"_index":".kibana","_type":"config","_id":"5.6.8","_score":1.0,"_source":{"buildNum":15616}}]}}

Thank you.
Fabio

**Comment by fabiofilz** [comment]
Hi,

As it used http instead of https, I disabled the option "Require HTTPS for all traffic to the domain" in AWS ElasticSearch and also changed the Port to 80 instead of 443 and it looks that it is working now.

 2020/07/30 10:46:10 Received 200 from http://vpc-datahub-es-pt-XXXXXXXXXXXXXXX.eu-central-1.es.amazonaws.com:80

Regarding to logs:

ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.

Thank you.
Fabio

**Comment by mars-lan** [comment]
@fabiofilz glad that you got it working in the end. I believe @shakti-garg-saxo & his team is working on adding https support for Elasticsearch. The logging level issue is tackled separately in https://github.com/linkedin/datahub/issues/1760.

**Comment by jplaisted** [comment]
Sorry, to clarify, what service is saying this?

```
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
```

**Comment by fabiofilz** [comment]
Hi @jplaisted, the datahub-gms-deployment service.

**Comment by camelliazhang2018** [comment]
@fabiofilz That is great news, sorry that the lack of logging makes debugging harder and thanks for sharing the information with us. Please let us know if the rest of search queries work as expected.

**Comment by camelliazhang2018** [comment]
> @fabiofilz glad that you got it working in the end. I believe @shakti-garg-saxo & his team is working on adding https support for Elasticsearch. The logging level issue is tackled separately in #1760.

@mars-lan Is there a ticket for enabling https support for Elasticsearch?

**Comment by camelliazhang2018** [comment]
> @camelliazhang2018, When I upgrade the ES version from 5.6.16 to 6.8.11, the ES console will prompt some warnings:
> 
> ```
> # ES console prompts when the service starts
> [2020-07-28T09:41:29,044][WARN ][o.e.d.a.c.NGramTokenizerFactory] [b0pdh5T] Deprecated big difference between max_gram and min_gram in NGram Tokenizer,expected difference must be less than or equal to: [1]
> [2020-07-28T09:41:33,565][WARN ][o.e.d.r.a.a.i.RestGetMappingAction] [b0pdh5T] [types removal] The parameter include_type_name should be explicitly specified in get mapping requests to prepare for 7.0. In 7.0 include_type_name will default to 'false', which means responses will omit the type name in mapping definitions.
> 
> [2020-07-28T09:41:31,885][WARN ][o.e.c.m.MetaDataMappingService] [b0pdh5T] [datasetdocument] re-syncing mappings with cluster state because of types [[doc]]
> [2020-07-28T09:41:33,899][WARN ][o.e.c.m.MetaDataMappingService] [b0pdh5T] [dataprocessdocument] re-syncing mappings with cluster state because of types [[doc]]
> [2020-07-28T09:41:36,965][WARN ][o.e.c.m.MetaDataMappingService] [b0pdh5T] [corpuserinfodocument] re-syncing mappings with cluster state because of types [[doc]]
> 
> # When searching for keywords
> [2020-07-28T09:50:34,656][WARN ][o.e.d.c.ParseField       ] [b0pdh5T] Deprecated field [disable_coord] used, replaced by [disable_coord has been removed]
> [2020-07-28T09:50:34,656][WARN ][o.e.d.s.a.I.Parser       ] [b0pdh5T] Deprecated aggregation order key [_term] used, replaced by [_key]
> [2020-07-28T09:50:34,657][WARN ][o.e.d.s.a.I.Parser       ] [b0pdh5T] Deprecated aggregation order key [_term] used, replaced by [_key]
> ```
> 
> Although it does not seem to affect the work at present, it is best to adjust the index configuration to ensure that there will be no problems.

Glad to see that works, and you can ignore those warnings if you decide to keep ES6.x. Upgrade to 6.x/7.x is definitely on our road map but not on priority list yet. Is there any specific feature you are looking for that is not currently supported?

**Comment by mars-lan** [comment]
> > @fabiofilz glad that you got it working in the end. I believe @shakti-garg-saxo & his team is working on adding https support for Elasticsearch. The logging level issue is tackled separately in #1760.
> 
> @mars-lan Is there a ticket for enabling https support for Elasticsearch?

Created https://github.com/linkedin/datahub/issues/1779 to track this. @shakti-garg-saxo can you confirm that you plan to work on it?

**Comment by cobolbaby** [comment]
@camelliazhang2018 The motivation for the upgrade comes from our ES maintainers, who want to unify the version as much as possible.

**Comment by mars-lan** [comment]
@cobolbaby are you guys using DH in your production or just building POC? What's the name of your company? Mind if we add it to the list here? https://github.com/linkedin/datahub#adoption

**Comment by cobolbaby** [comment]
Yes, we are currently building data warehouse for smart factory and looking for a metadata management platform to optimize the data warehouse model design and solve data quality issues.

Never mind, my company name is Inventec.

**Comment by mars-lan** [comment]
> Yes, we are currently building data warehouse for smart factory and looking for a metadata management platform to optimize the data warehouse model design and solve data quality issues.
> 
> Never mind, my company name is Inventec.

Cool. I'm aware of Inventec. Added it to the "building POC & evaluating list". Please let us know once you've adopted DataHub so we can upgrade your company to the "adopter list".

**Comment by mars-lan** [comment]
Same story for you @fabiofilz. Please let us know if you'd like us to add your company to the list.

**Comment by themightylaz** [comment]
Hi, yes, that's ok. Company name is Kindred Group.

**Comment by jjoyce0510** [comment]
Bumping the thread. Has this been resolved?

**Comment by jjoyce0510** [comment]
cc. @dexter-mh-lee To take a look.

**Comment by jjoyce0510** [comment]
@shirshanka This should have been fixed along with the ES7 migration. Let's close the ticket!
