### ISSUE TITLE
Dataset schema informance show nothing

### ISSUE THREAD

**Issue by cobolbaby** [linkedin/datahub#1728]
**Describe the bug**

After I execute the metadata-ingestion/sql-etl/postgres_etl.py，I can get the related datasets. But the schema informance show nothing. Is this reasonable?

![2020-07-09 18-54-16屏幕截图](https://user-images.githubusercontent.com/11460848/87031360-9c439d00-c215-11ea-921b-32ecdbf793d1.png)

**Comment by hgcummings** [comment]
I had the same issue with the sql-etl scripts, and after some debugging discovered that the JavaScript frontend doesn't display the schema if the `platformSchema.tableSchema` in the `SchemaMetadata` is falsy. This is always the case for MCEs created by `sql-etl/common.py`, since it hardcodes the tableSchema to `''`.

After updating `sql-etl/common.py` to set the `tableSchema` to something truthy (i.e. not null or empty), the schema then showed up in the front-end. (Note that `mysql-etl/mysql-etl.py` already does this.)

I'd be happy to create a PR for this, but I'm not sure exactly what value is appropriate to put into tableSchema. The doc comment on tableSchema says it's human-readable JSON, but I don't think it's actually parsed as JSON anywhere. The `mysql-etl` script sets it to a string representation of a row from the information_schemas table. I just set it to the SQL DDL definition of the table.

**Comment by hgcummings** [comment]
Tagging @keremsahin1 in from discussion on Slack. I'm happy to create a PR to populate the tableSchema field, but would you be able to advise as to the correct contents of this field? The document says it should be human-readable JSON but I'm not sure if that's actually necessary or relevant in all cases. Options include:

1. For RDBMSs, populate `tableSchema` with the table DDL definition (and update the doc comment on `tableSchema` to remove references to JSON)
2. For RDBMSs, populate `tableSchema` with some JSON representation of the underlying schema (not sure what this would look like, and it could be quite a lot of work to generalise across different RDBMSs, although probably achievable as long as we can lean on the SqlAlchemy model of the DB)

**Comment by mars-lan** [comment]
@hgcummings DDL would suffice IMO. However, SQL Alchemy seems to lack a portable way to retrieve DDL so chances are you may need to add system-specific hooks to the current scripts under `sql-etl`. Look forward to the PR!

**Comment by mars-lan** [comment]
@cptran777 please take a look at the frontend issue. Maybe we should test for nullability instead of falseiness?

**Comment by mars-lan** [comment]
@cobolbaby seems like this has been fixed in the latest frontend. Could you verify and close it?

**Comment by cobolbaby** [comment]
The value of `tableSchema` in `common.py` is still ''. Is the front-end code compatible with this situation? If possible, please clarify the relevant code.

**Comment by mars-lan** [comment]
@cptran777 I believe you've fixed handling of empty schema here?

**Comment by cptran777** [comment]
If the return value of `rawSchema` is an empty string, then we will consider it to have a schema. However `rawSchema` cannot be null or undefined.

**Comment by mars-lan** [comment]
@cptran777 can we close this now?
