### ISSUE TITLE
`dataset` and `datasetkey` in `gms.api` relates to its model entity in `metadata-models`?

### ISSUE THREAD

**Issue by liangjun-jiang** [linkedin/datahub#1746]
I am curious about the [dataset](https://github.com/linkedin/datahub/blob/master/gms/api/src/main/pegasus/com/linkedin/dataset/Dataset.pdl) and [datasetkey](https://github.com/linkedin/datahub/blob/master/gms/api/src/main/pegasus/com/linkedin/dataset/DatasetKey.pdl) in `gms.api` related to `dataset` entity in `metadata-models`.
The same questions applies to `dataprocess` and `corpuser`.

My understanding is that `datasetkey` in `gms.api` contains how an Urn is defined. `dataset` in `gms.api` contains those optional aspects. It seems working well for `corpuser` from this understanding. But for `dataset` in `gms.api`, it has information which is not related to `aspects`. 

I also searched around, and it seems that generated classes for `datasetkey` and `dataset` in `gms.api` are never used anyway - I might be wrong .

**Comment by mars-lan** [comment]
You're correct that dataset](https://github.com/linkedin/datahub/blob/master/gms/api/src/main/pegasus/com/linkedin/dataset/Dataset.pdl) and [datasetkey](https://github.com/linkedin/datahub/blob/master/gms/api/src/main/pegasus/com/linkedin/dataset/DatasetKey.pdl) are used solely in the context of the [datasets rest.li endpoint](https://github.com/linkedin/datahub/blob/master/gms/impl/src/main/java/com/linkedin/metadata/resources/dataset/Datasets.java). Due to legacy reason we have some fields in `dataset` that are not proper GMA aspect. We're in the process of migrating those dependencies so hopefully in a few more releases it'll be as clean as `corpuser`.
