### ISSUE TITLE
问题简介I want to ask, can datahub only be started by docker?

### ISSUE THREAD

**Issue by Wandering-Swordsman** [linkedin/datahub#1796]
I want to ask, can datahub only be started by docker?

**Comment by mars-lan** [comment]
@clojurians-org has contributed nix-based virtualization for DataHub: https://github.com/linkedin/datahub/tree/master/contrib/nix

Since the compiled binaries are simply JAR files, you can also launch them using Java directly. See https://github.com/linkedin/datahub/blob/master/docker/datahub-gms/start.sh#L9 for an example launch command.

**Comment by Wandering-Swordsman** [comment]
Thank you very much

**Comment by mars-lan** [comment]
Assume the question has been answered. Feel free to reopen otherwise.
