### ISSUE TITLE
Social function issues introduced by the latest version of the frontend

### ISSUE THREAD

**Issue by cobolbaby** [linkedin/datahub#1824]
The latest version of the datahub-frontend will output some error messages on the console when doing web page operations.

![2020-08-27 14-59-00屏幕截图](https://user-images.githubusercontent.com/11460848/91408063-ce689700-e875-11ea-96fd-a316a80a9eaa.png)

Check the error message, you'll find that the front-end seems to support some friendly social functions, but the mid-tier does not provide corresponding support.  When will the related functions be released?

In addition, judging from the http requests, the front end repeatedly pushed some requests, which is obviously some potential problems.

**Comment by cptran777** [comment]
Hey @cobolbaby , thanks for reporting this. We're aware of this un-ideal change but it shouldn't be blocking or disruptive so that's why it's currently checked in. Unfortunately, things will be a little weird on the frontend/UI while we transition into a new open source workflow after allowing it to be stale for so many months. However, we're currently working through a lot of these pain points and I think in the long run it'll be quite an exciting new development where we can constantly evolve along with the community and feedback. 

Anyway, a little bit of a tangent there, we'll be working on cleaning this up as well, instead of relying on the un-ideal situation, and it'll be optional (if you want to implement support) and not mandatory + erroring out.

**Comment by cobolbaby** [comment]
![2020-09-04 11-45-54屏幕截图](https://user-images.githubusercontent.com/11460848/92197401-33d70c00-eea4-11ea-9740-59ba55362766.png)
The latest commit fixes the previous one but introduces new bugfix.

**Comment by cptran777** [comment]
Hey @cobolbaby,

I think this issue is related to: https://github.com/linkedin/datahub/issues/1827. Since the social function issue has been fixed and the other issue is being tracked, I'll close this issue so that we have a cleaner workflow for tracking issues.
