### ISSUE TITLE
Datasets rights management

### ISSUE THREAD

**Issue by q2515045** [linkedin/datahub#1852]
**Is your feature request related to a problem? Please describe.**
I don't want to see all datasets being used by everyone

**Describe the solution you'd like**
Can you add features so that everyone can only see their own datasets

**Comment by jplaisted** [comment]
We have that already! You have a profile page, and under that is "Datasets I own".

![Screen Shot 2020-09-07 at 1 16 39 PM](https://user-images.githubusercontent.com/1565017/92415142-68e59780-f10c-11ea-9797-3ca3efe53954.png)


![Screen Shot 2020-09-07 at 1 17 52 PM](https://user-images.githubusercontent.com/1565017/92415159-8ca8dd80-f10c-11ea-964e-210167614dd4.png)



Any suggestions as to how to make this more discoverable, since this seems to be a discoverability issue.

**Comment by camelliazhang** [comment]
@jplaisted I think @q2515045 is probably referring to data privacy? If that's the case, we have access control for datasets.

**Comment by mars-lan** [comment]
Will let @q2515045 clarify what he/she means exactly. As far as I can see there are 3 possibilities

1. I want to see only datasets I own
2. I want to see only datasets I have access to
3. I should be allowed to see only a subset of all datasets that I own/have access to

**Comment by mars-lan** [comment]
Ping @q2515045

**Comment by mars-lan** [comment]
One ping @q2515045. Will close this issue by 10/19 if there's no response before then.
