### ISSUE TITLE
Add onboarding document for deltas

### ISSUE THREAD

**Issue by mars-lan** [linkedin/datahub#1906]
Currently there's only high-level doc on [metadata delta](https://github.com/linkedin/datahub/blob/master/docs/what/delta.md) without a concrete example showing the onboarding process.

**Comment by jplaisted** [comment]
We're not supporting this anymore with mxe v5, right? Maybe we shouldn't document it, intentionally? :p Try to ensure less people are on it when we make the switch?

**Comment by mars-lan** [comment]
We'll be supporting that in MXEv5. Deltas & Aspects will still need to be annotated separately.

**Comment by mars-lan** [comment]
Also seems like the MCE processor isn't handling delta correctly yet: https://github.com/linkedin/datahub/blob/master/metadata-jobs/mce-consumer-job/src/main/java/com/linkedin/metadata/kafka/MetadataChangeEventsProcessor.java#L56

**Comment by grantatspothero** [comment]
Delta support would be very helpful in order to ingest downstream lineage deltas. 

Unlike upstream lineage which is completely determined by how a dataset is built, downstream lineage is distributed because one dataset can be utilized in multiple places by multiple different systems. Thus it is hard to get a complete datasetsnapshot of downstream lineage when doing metadata ingestion since you would need to find all usages of a dataset scattered across many systems and then merge those into a single MetadataChangeEvent.

Right now this is blocking us (SpotHero) from setting downstream lineage.

**Comment by mars-lan** [comment]
@grantatspothero I think you may have misunderstood how Downstream & Upstream work. We currently only capture upstream in an aspect because

1. the full list of upstream is generally available at the time of collection
2. the list of upstream datasets is finite, whereas the list of downstream can be unbounded

We index the upstream as edges in the graph and traverse the graph to figure out the downstream. In other words, there's no need to capture the downstream explicitly. See https://github.com/linkedin/datahub/blob/master/metadata-builders/src/main/java/com/linkedin/metadata/builders/graph/relationship/DownstreamOfBuilderFromUpstreamLineage.java for more details.

**Comment by grantatspothero** [comment]
@mars-lan That makes sense you can infer downstream lineage from upstream lineage. 

I jumped to conclusions about needing to set downstream lineage explicitly because it was not showing up in the UI. I will try to debug why that inference of downstream lineage is not making its way into UI and let you know what I find 👍

**Comment by grantatspothero** [comment]
@mars-lan Downstream lineage not showing up was an unrelated problem due to configuration problems with our neo4j cluster sorry about the red herring.

**Comment by jjoyce0510** [comment]
Is anyone working on this one? Seems like deltas are _not_ a formally supported concept in the OSS DataHub.

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
