### ISSUE TITLE
Ability to define downstream lineage for datasets in the MCE message

### ISSUE THREAD

**Issue by shakti-garg-saxo** [linkedin/datahub#2052]
**Is your feature request related to a problem? Please describe.**
Currently, MCE -> Snapshot -> Dataset -> DatasetAspects only allow to define upstream lineage. This request is to also support defining downstream lineage as a dataset aspect.

**Describe the solution you'd like**
It should be a small change by importing already existing, DownstreamLineage.pdl to the DatasetAspect.pdl.

**Comment by shakti-garg-saxo** [comment]
Happy to contribute back, if you agree with the feature request and approach.

**Comment by mars-lan** [comment]
Since one can derive the downstream from all the upstream info, there's no need to capture them separately. DataHub currently uses the graph DB to query downstream information: https://github.com/linkedin/datahub/blob/master/gms/impl/src/main/java/com/linkedin/metadata/resources/dataset/DownstreamLineageResource.java#L67

**Comment by jplaisted** [comment]
Closing for now, assuming this was answered (thanks, Mars). Having only one kind of edge in the metadata / ecosystem simplifies things.

**Comment by shakti-garg-saxo** [comment]
@mars-lan @jplaisted Thanks for quick reply. Let me present the use case for which I made this request(I should have  done this earlier).

From our source systems, we are getting lineage between datasets A and B. metadata of dataset A is known to us as it is part of source system which is already onboarded to the datahub. On contrary, dataset B belongs to some source for which we don't have any information in the system. As a result, we can't define this lineage metadata using upstream lineage of dataset B.
If we do create dataset B, it doesn't have schema or relevant metadata. In ideal scenario, we are expecting only lineage metadata visible but not the dataset B as it can lead to misunderstanding and unnecessary compliance alerts.

Though I agree that having only one kind of edge simplifies the interface, imo it is also about flexibility to define metadata. 
Please share your thoughts or if you can help me with better approach in the above scenario.

**Comment by shirshanka** [comment]
@shakti-garg-saxo: Even in the case where you attach lineage information to A (instead of B), you would need a dataset-urn for B. 

The meta-model allows you to have nodes in the graph where aspects are not defined and are optional, so it should be possible for you to create the entity B without having to attach schema / other metadata to it.  

One way, we have handled this differentiation of datasets that are known fully versus known barely :) is by assigning them a platform called "external". You could choose something else as a marker platform, and ensure that your UI doesn't render datasets from that platform (if that is important to you). 

One interesting side benefit of having these kind of datasets be visible, is that users often ask for more information about them, which leads to the team that owns the platform signing up to publish metadata for those platforms. So you might actually unlock better metadata coverage through this!

HTH

**Comment by camelliazhang** [comment]
@shakti-garg-saxo This is an interesting topic. The current lineage model kind of assuming datasets have equal knowledge about lineage, now we are looking at the cases where certain nodes is holding more info; while some others may only be needed as bridges (they could be important though, to help uncover unknown lineages). For your use case, seems that we do need to introduce extra aspect such as downstream. The downside are:
  1. You may end up storing duplicated info in the document store for the nodes that have both downstream & upstream info. 
  2. It may not work for high cardinality relationships: https://github.com/linkedin/datahub/blob/master/docs/advanced/high-cardinality.md

**Comment by shakti-garg-saxo** [comment]
Agree on all the above points. We will then continue on our existing approach of tagging unknown datasets with some markers.
@shirshanka agree on your suggestion to keep them visible to users for more push to compliance.
@camelliazhang Thanks for the pointing out technical downsides(I certainly overlooked them in my analysis :) )
