### ISSUE TITLE
TypeScript Ingestion SDK Generation

### ISSUE THREAD

**Issue by swcho** [linkedin/datahub#2703]
Thank you for great work!

**Is your feature request related to a problem? Please describe.**
TypeScript delivers more concrete type information than python.
As one of the DataHub's main selling point is type safety, I think it would be great to support ingestion for type safe language.
When we think about TypeScript's popularity and its ubiquity, ingesting metadata in type safe way by TypeScript would give DataHub more attention and lead to broaden ecosystem.

**Describe the solution you'd like**
TypeScript Ingestion SDK Generation (Including No Code Metadata Schema)

**Describe alternatives you've considered**
Ingestion examples by TypeScript would be helpful.
Not just putting snapshot json, but putting snapshot with proper type definition assisted.

**Additional context**
May be this would be helpful for type generation.
https://www.npmtrends.com/@chasdevs/avro-to-typescript-vs-@degordian/avro-to-typescript-vs-avro-typescript-vs-avro-tsc

**Comment by hsheth2** [comment]
Is there a reason you don't want to or can't use the Python ingestion framework? It currently uses codegen for similar effect, and is fully annotated with Python type annotations (example: https://github.com/linkedin/datahub/blob/master/metadata-ingestion/src/datahub/metadata/schema_classes.py). Those type annotations can be statically checked using a tool like `mypy`.

At the same time, we'd be happy to accept contributions in this area

**Comment by swcho** [comment]
@hsheth2 

In Python, is it possible to have some code assist on IDE?

At least, I just hope to have full picture of how snapshot structured and how to make snapshot data.
For me, it's bit time consuming to understand actual snapshot structure.

If TypeScript definition can be utilized on this matter, it would be more easier as schema can be described more clear way.
Moreover, you can send snapshot on browser.

Thank you.

**Comment by hsheth2** [comment]
The snapshot structure definitely requires a bit of work in order to grok. In brief, we've got MetadataChangeEvents, which each contain a proposedSnapshot that is an "entity type", and each entity has a unique identifier URN and any number of aspects.

As for code assistance in an IDE, I'm using vscode's standard install, and automatically get type hints and completion:
![image](https://user-images.githubusercontent.com/12566801/122594418-d586ae80-d01b-11eb-843a-c5d9eb65ccd9.png)

That said, I think having an additional, TypeScript-native interface would be great, and we'd be happy to take contributions :)

**Comment by swcho** [comment]
@hsheth2 

It's seems datahub changes dramatically every release.
Especially, feature like no code schema generation would impact a lot on ingestion part I guess.
Do you think it is right time to investigate TypeScript generation?
Or would it be good for waiting some big changes?

**Comment by hsheth2** [comment]
I think that if we do a Typescript SDK, it would be best to rely on codegen so that it can easily stay in sync with the rest of the models. This is the approach that the Python framework takes as well. 

Not sure if it’s the right time - my impression is that the Python ingestion framework is working pretty well for people right now.

**Comment by maggiehays** [comment]
Hi folks!

We are now managing feature requests through our new portal to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to reach out to me on DataHub Slack with any questions!
