### ISSUE TITLE
Support map fieldType for  @Searchable pdl annotation

### ISSUE THREAD

**Issue by amorskoy** [linkedin/datahub#2871]
Taking `DatasetProperties.pdl` as en example.
At this moment, I have no chance to search inside `customProperties` (inherited from `CustomProperties.pdl`).

Thus, I can not to search like "Find dataset having property 'sales_person' equal to `Andrey` ".

I may suppose, that search by properties is expected to be a common use case for metadata consumers

**Comment by shirshanka** [comment]
Hi @amorskoy this is a common request, thanks for making it :) 

One thing we want to be careful about is auto-indexing each key by default because it could lead to an explosion in terms indexed in elastic, e.g. if someone is logging a high cardinality key like "job-id" or a very verbose key like "dag-details" in Airflow etc. 
We're thinking about a safe way to introduce this capability. @dexter-mh-lee will reply back on this issue.

**Comment by dexter-mh-lee** [comment]
@amorskoy Sorry about the late reply. This feature was added a month ago, where you can search for "key1=value1" query to find entities with the property. For efficiency reasons, we only support case-insensitive exact matches and values that are less than 200 characters

**Comment by maggiehays** [comment]
Hi folks,

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
