### ISSUE TITLE
How it is supposed to search using tags?

### ISSUE THREAD

**Issue by Light310** [linkedin/datahub#3105]
Hello! 
We've tried to search datasets with a specific tag, but it looks like it is not working as intended. Though in the drop-down list it shows that it is using the specific tag, nevertheless it shows all the datasets as if it was a simple search (for example, if u're searching for tag "order" it shows you datasets with "order" in name and columns).
Is it a bug or there is some weird logic in how to use it?

**Comment by dexter-mh-lee** [comment]
How are you searching? Query "tag:order" should restrict it to datasets with the tag

**Comment by Light310** [comment]
1st screenshot : I search for "car" and I can see a tag named "car", but when I click on it, I can see all the datasets as if I was searching for "car" not in tags.

2nd screenshot: I search for "tag:car" and it is searching for "tag" actually.
Both not working as intended.

![tag_search_bug](https://user-images.githubusercontent.com/13537643/129858081-0c4050fb-9c54-45ee-9da3-53ec89795089.png)

**Comment by dexter-mh-lee** [comment]
Autocomplete is not search. So pressing enter after typing "tag:car" should land you on the intended page. Unfortunately, we don't have good autocomplete when using filtered search like "field:value". However, search still works correctly. 

For the above case, putting it in the backlog to make sure we search for "car" tag (i.e. search tag:car) instead of searching for query "car"

**Comment by dexter-mh-lee** [comment]
Sorry about the confusion. It was tags:<TAG> not tag:<TAG>

**Comment by Light310** [comment]
Okay, with "tags" it is working, thank you
