### ISSUE TITLE
How to model cluster / instance identifiers?

### ISSUE THREAD

**Issue by nickwu241** [linkedin/datahub#3529]
1. What is the current recommended workaround for adding cluster/instance identifiers to data sources such as mysql and snowflake to avoid naming collisions?

DataHub will natively support this at some point (maybe by EoY) https://datahubspace.slack.com/archives/CUMUWQU66/p1635373895081300

2. Similarly, are there any suggestions for modeling out data stored in different geographical regions? e.g. extending the `FabricType`? Adding it through tags?

DataHub has alluded to eventually supporting "containers" where you can put related data which might be where to add this? https://datahubspace.slack.com/archives/C02FWNS2F08/p1634560665377600

**Comment by jjoyce0510** [comment]
Hi @nickwu241! Yes this is a very pressing issue that we are finally beginning work on. It's a major problem since it will require the development of a new key structure. Today, there is no ideal workaround besides applying a transformer to embed the fabric into the Dataset name or elsewhere (terrible, I know). 

The solution we're working towards is to change the information captured in dataset (and other asset) urns:

- platform type
- platform instance id -- a custom identifier for a particular instance 
- coordinates, or unique name within the system

With the new URN structure, we'll be updating the Ingestion Sources to be configurable to produce either the new or old urn format.

**Comment by shirshanka** [comment]
Hi @nickwu241, we currently have work in flight to support this functionality; please refer to [this feature request](https://feature-requests.datahubproject.io/b/User-Experience/p/support-multiple-platfrom-instances) to keep track of progress. I'll close out this issue in the meantime.
